ProjetoAdotaPet/src/main/java/br/vianna/aula/jsf/model/Adotante.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.vianna.aula.jsf.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 *
 * @author PedroVitorDev
 */
@Entity
@Table(name = "adotante")
public class Adotante {

    
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    private int idadotante;
    
    @NotNull
    private String nome;
    
    @NotNull
    @Temporal(TemporalType.DATE)
    private Date dataNasc;
    
    @NotNull
    private int salario;
    
    @NotNull
    private ArrayList<Pet> p;

    public Adotante() {
    }

    public Adotante(int idadotante, String nome, Date dataNasc, int salario, ArrayList<Pet> p) {
        this.idadotante = idadotante;
        this.nome = nome;
        this.dataNasc = dataNasc;
        this.salario = salario;
        this.p = p;
    }

    public int getIdadotante() {
        return idadotante;
    }

    public void setIdadotante(int idadotante) {
        this.idadotante = idadotante;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Date getDataNasc() {
        return dataNasc;
    }

    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }

    public int getSalario() {
        return salario;
    }

    public void setSalario(int salario) {
        this.salario = salario;
    }

    public ArrayList<Pet> getP() {
        return p;
    }

    public void setP(ArrayList<Pet> p) {
        this.p = p;
    }

    

}

ProjetoAdotaPet/src/main/java/br/vianna/aula/jsf/model/Cachorro.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.vianna.aula.jsf.model;

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 *
 * @author PedroVitorDev
 */
@Entity
@PrimaryKeyJoinColumn(name = "idcachorro")
public class Cachorro extends Pet {

    
  @NotNull
  @Enumerated(EnumType.STRING)
  private PorteCachorro porte;  
    
    
  @NotNull
  @Enumerated(EnumType.STRING)
  private RacaCachorro raca;

    public Cachorro() {
    }
  
    public Cachorro(PorteCachorro porte, RacaCachorro raca) {
        this.porte = porte;
        this.raca = raca;
    }

    public Cachorro(PorteCachorro porte, RacaCachorro raca, int idpet, String nome, String sexo, Date dataNasc, boolean ehDomesticado, boolean ehVacinado, boolean ehCadastrado, Adotante adotante) {
        super(idpet, nome, sexo, dataNasc, ehDomesticado, ehVacinado, ehCadastrado, adotante);
        this.porte = porte;
        this.raca = raca;
    }

    public PorteCachorro getPorte() {
        return porte;
    }

    public void setPorte(PorteCachorro porte) {
        this.porte = porte;
    }

    public RacaCachorro getRaca() {
        return raca;
    }

    public void setRaca(RacaCachorro raca) {
        this.raca = raca;
    }

       

}

ProjetoAdotaPet/src/main/java/br/vianna/aula/jsf/mb/CadastroPetMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.vianna.aula.jsf.mb;

import br.vianna.aula.jsf.dao.CachorroDao;
import br.vianna.aula.jsf.dao.GatoDao;
import br.vianna.aula.jsf.dao.PetDao;
import br.vianna.aula.jsf.model.Cachorro;
import br.vianna.aula.jsf.model.Gato;
import br.vianna.aula.jsf.model.PelagemGato;
import br.vianna.aula.jsf.model.Pet;
import br.vianna.aula.jsf.model.PorteCachorro;
import br.vianna.aula.jsf.model.RacaCachorro;
import br.vianna.aula.jsf.model.RacaGato;
import br.vianna.aula.jsf.model.dto.ListPetDTO;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import javax.faces.view.ViewScoped;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author PedroVitorDev
 */
@Component(value = "cadPetMB")
@ViewScoped
public class CadastroPetMB implements Serializable {

    private EStatusCrud status;

    private ArrayList<ListPetDTO> lista;

    private Pet animal;

    private String tipoEscolhido;

    private PorteCachorro[] porteCachorro;
    private RacaCachorro[] racaCachorro;
    private RacaGato[] racaGato;
    private PelagemGato[] pelagemGato;

   

    @Autowired
    private CachorroDao cacDao;

    @Autowired
    private GatoDao gatoDao;

    public CadastroPetMB() {

        status = EStatusCrud.VIEW;


        porteCachorro = PorteCachorro.values();
        racaCachorro = RacaCachorro.values();
        racaGato = RacaGato.values();
        pelagemGato = PelagemGato.values();

        inicializaAnimal();
        ((Cachorro) animal).setPorte(PorteCachorro.Pequeno);
        

//        lista = new ArrayList<>();
//        lista.add(new ListPetDTO("Fofinho", "Feminino", "Gato", "Zezin", true));
//        lista.add(new ListPetDTO("Bravão", "Masculino", "Cachorro", null, true));
//        lista.add(new ListPetDTO("Lili", "Feminino", "Cachorro", null, true));
//        lista.add(new ListPetDTO("Bolinho", "Masculino", "Gato", null, true));
//        lista.add(new ListPetDTO("Mostarda", "Masculino", "Cachorro", "Gustin", true));
//        lista.add(new ListPetDTO("Azulão", "Masculino", "Cachorro", null, true));
    }

    public void changeTipo() {

        System.out.println("chamou" + tipoEscolhido);
        if (tipoEscolhido.equalsIgnoreCase("c")) {
            animal = new Cachorro();
        } else {
            animal = new Gato();
        }

    }

    private void inicializaAnimal() {
        animal = new Cachorro();
//        animal.setNome("abc");
        animal.setSexo("Masculino");
        animal.setEhVacinado(true);
        animal.setDataNasc(new Date());
        tipoEscolhido = "c";
    }

    @PostConstruct
    public void init() {

        lista = getAllPets();

    }

    public void validaDataNascimento(FacesContext ct, UIComponent comp, Object value) {

        Date data = (Date) value;

        if (data.after(new Date())) {

            throw new ValidatorException(new FacesMessage(FacesMessage.SEVERITY_ERROR,
                    "Data incorreta", "A data não pode ser futura"));
        }

    }
    
    public String preparedEdit(int id, String tipo){
    
        status = EStatusCrud.EDIT;
        
        
         if (tipo.equalsIgnoreCase("Cachorro")) {
            animal = cacDao.get(id);
            tipoEscolhido = "c";
        } else {
            animal = gatoDao.get(id);
            tipoEscolhido = "g";
        }
               
        return "";
    
    }
        
     public String delete(int id, String tipo){
 
         FacesContext ct = FacesContext.getCurrentInstance();
         
         
         Pet aux = null;
         
         if(tipo.equalsIgnoreCase("Cachorro")){
            aux= cacDao.delete(id);
         }else{
            aux= gatoDao.delete(id);
         }
         
        lista = getAllPets(); 
         
        ct.addMessage("", new FacesMessage(aux.getNome()+" foi apagado com sucesso!!"));

        return "";
         
     } 
             
     
    
    
    public String salvar() {

        FacesContext ct = FacesContext.getCurrentInstance();

        if (animal instanceof Cachorro && ((Cachorro) animal).getPorte() == PorteCachorro.Grande) {
            ct.addMessage("", new FacesMessage("não aceitamos cachorro Grande"));
            return "";
        }

        String tp="";
        if (animal instanceof Cachorro) {

            cacDao.save((Cachorro) animal);
            tp="Cachorro";

        } else {
            gatoDao.save((Gato) animal);
            tp="Gato";
        }

        inicializaAnimal();

        status = EStatusCrud.VIEW;

        lista = getAllPets();
        
        ct.addMessage("", new FacesMessage(tp+" salvo com sucesso!!"));

        return "";

    }

    public String trocar() {

        status = EStatusCrud.INSERT;
        
        inicializaAnimal();
        
        return "";
    }

    public String voltar() {

        status = EStatusCrud.VIEW;

        return "";
    }

     private ArrayList<ListPetDTO> getAllPets() {
        
       ArrayList<ListPetDTO> lista = new ArrayList<>();
       
       lista.addAll(cacDao.getAllPets());
       lista.addAll(gatoDao.getAllPets());
       
       return lista;
        
    }
    
    
    
    
    public boolean isView() {

        return status == EStatusCrud.VIEW;
    }

    public EStatusCrud getStatus() {
        return status;
    }

    public void setStatus(EStatusCrud status) {
        this.status = status;
    }

    public ArrayList<ListPetDTO> getLista() {
        return lista;
    }

    public void setLista(ArrayList<ListPetDTO> lista) {
        this.lista = lista;
    }

    public Pet getAnimal() {
        return animal;
    }

    public void setAnimal(Pet animal) {
        this.animal = animal;
    }

    public String getTipoEscolhido() {
        return tipoEscolhido;
    }

    public void setTipoEscolhido(String tipoEscolhido) {
        this.tipoEscolhido = tipoEscolhido;
    }


    public PorteCachorro[] getPorteCachorro() {
        return porteCachorro;
    }

    public void setPorteCachorro(PorteCachorro[] porteCachorro) {
        this.porteCachorro = porteCachorro;
    }

    public RacaCachorro[] getRacaCachorro() {
        return racaCachorro;
    }

    public void setRacaCachorro(RacaCachorro[] racaCachorro) {
        this.racaCachorro = racaCachorro;
    }

    public RacaGato[] getRacaGato() {
        return racaGato;
    }

    public void setRacaGato(RacaGato[] racaGato) {
        this.racaGato = racaGato;
    }

    public PelagemGato[] getPelagemGato() {
        return pelagemGato;
    }

    public void setPelagemGato(PelagemGato[] pelagemGato) {
        this.pelagemGato = pelagemGato;
    }

   

}

ProjetoAdotaPet/src/main/java/br/vianna/aula/jsf/mb/CadastroUsuarioMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.vianna.aula.jsf.mb;

import br.vianna.aula.jsf.dao.UsuarioDao;
import br.vianna.aula.jsf.model.ETipoUsuario;
import br.vianna.aula.jsf.model.Usuario;
import br.vianna.aula.jsf.util.Utils;
import java.io.IOException;
import java.io.Serializable;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author PedroVitorDev
 */
@Component(value = "cadMB")
@RequestScoped

public class CadastroUsuarioMB {

    private Usuario user;

    @Autowired
    UsuarioDao userD;
    
    @Autowired    //injeçaõ de dependencia
    LoginMB login;
    

    public CadastroUsuarioMB() {

        user = new Usuario();

    }

    public String saveUser() {

        user.setTipo(ETipoUsuario.NORMAL);
        try {
            user.setSenha(Utils.md5(user.getSenha())); //passando a senha do cadastro pra md5
        } catch (NoSuchAlgorithmException ex) {

        }

        userD.save(user);

        user = new Usuario(); //retornar pagina em branco pra poder inserir um novo usuario

        login.setMsgAviso("Usuário criado com sucesso!!");
        
        return "login?facess-redirect=true"; //redirect

    }

    public Usuario getUser() {
        return user;
    }

    public void setUser(Usuario user) {
        this.user = user;
    }

}

ProjetoAdotaPet/src/main/java/br/vianna/aula/jsf/mb/LoginMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.vianna.aula.jsf.mb;

import br.vianna.aula.jsf.dao.UsuarioDao;
import br.vianna.aula.jsf.model.ETipoUsuario;
import br.vianna.aula.jsf.model.Usuario;
import br.vianna.aula.jsf.model.dto.UsuarioLogadoDTO;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import org.graalvm.compiler.lir.CompositeValue;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author PedroVitorDev
 */
@Component
@SessionScoped
public class LoginMB implements Serializable {

    private String nome, senha, msgErro, msgAviso;
    private boolean isLogado;
    private UsuarioLogadoDTO user; //Variavel auxiliar pra poder usar depois
    //guardando usuario logado na sessão

    @Autowired
    UsuarioDao userD;

    public LoginMB() {
        msgErro = msgAviso = "";
        isLogado = false;
        user = null;
    }

    public boolean isAdmin() {

        if (user == null) {
            return false;

        }
        return user.getTipo() == ETipoUsuario.ADMIN;

    }

    public boolean isNormal() {

        if (user == null) {
            return false;

        }
        return user.getTipo() == ETipoUsuario.NORMAL;

    }

    public String callCadastro() {

        return "cadastro?faces-redirect=true";

    }

    public String getMsgErro() {
        return msgErro;
    }

    public void setMsgErro(String msgErro) {
        this.msgErro = msgErro;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public boolean isIsLogado() {
        return isLogado;
    }

    public void setIsLogado(boolean isLogado) {
        this.isLogado = isLogado;
    }

    public String getMsgAviso() {
        return msgAviso;
    }

    public void setMsgAviso(String msgAviso) {
        this.msgAviso = msgAviso;
    }

    public UsuarioLogadoDTO getUser() {
        return user;
    }

    public void setUser(UsuarioLogadoDTO user) {
        this.user = user;
    }

}

ProjetoAdotaPet/src/main/java/br/vianna/aula/jsf/mb/TemplateMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.vianna.aula.jsf.mb;

import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author PedroVitorDev
 */
@Component
@RequestScoped
public class TemplateMB {

    public String logout() {

        // Pegando o controller, pedindo para limpar a sessão
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();

        return "index";

    }

    public String home() {

        return "index?faces-redirect=true";

    }
    
    public String cadastrarPet() {

        return "cadastropet?faces-redirect=true";

    }
    
    

}

ProjetoAdotaPet/src/main/java/br/vianna/aula/jsf/mb/ValidaLoginMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.vianna.aula.jsf.mb;

import br.vianna.aula.jsf.dao.UsuarioDao;
import br.vianna.aula.jsf.model.ETipoUsuario;
import br.vianna.aula.jsf.model.Usuario;
import br.vianna.aula.jsf.util.Utils;
import java.io.IOException;
import java.io.Serializable;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author PedroVitorDev
 */
@Component
@RequestScoped

public class ValidaLoginMB {

    @Autowired
    UsuarioDao userD;
       
    @Autowired
    private LoginMB loginMb;

    public String verificaPassword() {

        loginMb.setUser(userD.existeUsuario(loginMb.getNome(), loginMb.getSenha()));

        if (loginMb.getUser() != null) {
            loginMb.setIsLogado(true);

            return "index";

        } else {
            loginMb.setMsgErro("login ou senha incorreta!!");
            loginMb.setNome("");
            loginMb.setSenha("");

            return "";
        }

    }
}

ProjetoAdotaPet/src/main/webapp/cadastro.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"  
      >
    <!-- Extraindo -->


    <head>
        <title>Cadastra-se Adota Pet</title>
        
         <link rel="icon" type="image/png" href="images/favicon.ico"  />
        <!--===============================================================================================-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css" />
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/animsition@4.0.2/dist/css/animsition.min.css" />
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="css/login.css" />
        
    </head>
    <body>

        <div class="container-fluid corpo">
            <div class="row justify-content-md-center h-100 p-5">
                <div class="card-wrapper">
                    <div class="brand text-center">
                        <h1 class="logo-badge text-whitesmoke"><span class="fa fa-user-circle"></span></h1>
                        <!--<img src="img/logo.jpg" alt="logo">-->
                    </div>
                    <div class="card fat">
                        <div class="card-body">
                            <h4 class="card-title">Cadastro</h4>
                            <h:form >
                               
                                
                                
                                 <div class="form-group">

                                     <label for="email">Nome:</label>
                                     <h:inputText class="form-control" value="#{cadMB.user. nome}" />      

                                 </div>

                                 <div class="form-group">

                                     <label for="email">Email:</label>
                                     <h:inputText class="form-control" value="#{cadMB.user.email}" />      

                                 </div>

                                 <div class="form-group">

                                     <label for="email">Login:</label>
                                     <h:inputText class="form-control" value="#{cadMB.user.login}"  />      

                                 </div>

                                 <div class="form-group">

                                     <label for="email">Senha:</label>
                                     <h:inputSecret class="form-control" value="#{cadMB.user.senha}"  />      

                                 </div>

                                <h:commandButton class="btn-primary" value="Salvar" 
                                                 action="#{cadMB.saveUser()}"/>
                                
                                
                                                                          
                            </h:form>
                        </div>
                    </div>
                    <div class="footer text-center">
                        POOA 2021
                    </div>
                </div>
            </div>
        </div>


        <!--===============================================================================================-->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

        <!--===============================================================================================-->
        <script src="https://cdn.jsdelivr.net/npm/animsition@4.0.2/dist/js/animsition.min.js"></script>
        <!--===============================================================================================-->

    </body>
</html>

ProjetoAdotaPet/src/main/webapp/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./template.xhtml">


    <ui:define name="body">
        Home
    </ui:define>

</ui:composition>

ProjetoAdotaPet/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./template.xhtml">

    <ui:define name="title">

        #{indexMb.nomeProjeto}   

    </ui:define>
    <ui:define name="header">
    </ui:define>

    <ui:define name="body">
        <h1> Conteúdo Principal </h1>
        <h2> Olá #{loginMB.user.nome} </h2>
        <h2>Tipo: #{loginMB.user.tipo} </h2>
    </ui:define>


</ui:composition>

ProjetoAdotaPet/src/main/webapp/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <!--        <h:outputStylesheet name="./css/default.css"/>
                <h:outputStylesheet name="./css/cssLayout.css"/>-->

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />
        <!--===============================================================================================-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic.min.css" integrity="sha512-LeCmts7kEi09nKc+DwGJqDV+dNQi/W8/qb0oUSsBLzTYiBwxj0KBlAow2//jV7jwEHwSCPShRN2+IWwWcn1x7Q==" crossorigin="anonymous" />
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css" />
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="css/home.css" />

        <script src="https://code.jquery.com/jquery-3.5.1.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

        <title> <ui:insert name="title">Adota Pet</ui:insert> </title>
    </h:head>

    <h:body>

        <header>
            <nav class="navbar navbar-inverse navbar navbar-dark bg-dark fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="btn btn-dark navbar-toggle pull-left menu-toggle"  data-target="#side-bar">
                            <i class="oi oi-menu"></i>
                        </button>
                        <a class="navbar-brand " href="#">Adota Pet</a>
                    </div>
                </div>
            </nav>
        </header>
        <input type="hidden" nome="ac" value="cadTime"/>    
        <div class="layout-main"> 

            <aside class="wrapper" id="side-bar">
                <nav id="menu" class="sidebar sidebar-open">
                    <ul class="nav nav-pills">
                        <li class="nav-item">
                            <h:form> 

                                <h:commandLink class="nav-item" value="Home" action="#{templateMB.home()}" />
                                <!-- gerando href -->

                            </h:form>     
                        </li>
                    </ul>
                    <ul class="nav nav-pills">
                        <li class="nav-item"><span class="nav-link active" >Administração</span></li>
                        <li class="nav-item">
                            <h:form> 

                                <h:commandLink class="nav-item" value="Cadastrar Pet" action="#{templateMB.cadastrarPet()}" />
                                <!-- gerando href -->

                            </h:form>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link"
                               href="control?ac=listaTimes"> <i class="oi oi-cart"></i> <span>Cadastrar Adotante</span>
                            </a>
                        </li>

                    </ul>
                    <ul class="nav nav-pills">
                        <li class="nav-item"><span class="nav-link active" >Geral</span></li>


                        <h:panelGroup rendered="#{loginMB.admin }">

                            <li class="nav-item">
                                <a class="nav-link">
                                    <span>Adotar Pet</span>
                                </a>
                            </li>   

                        </h:panelGroup>

                        <li class="nav-item">
                            <a class="nav-link">
                                <span>Acompanhar Pet</span>
                            </a>
                        </li>    

                        <li class="nav-item"><span class="nav-link active" >Relatório</span></li>

                        <li class="nav-item">
                            <a class="nav-link">
                                <i class="oi oi-cart"></i> <span>Adoções</span>
                            </a>
                        </li>

                        <li class="nav-item">    
                            <h:form>  

                                <h:commandLink class="nav-link" action="#{templateMB.logout()}">
                                    <i class="oi oi-account-logout"></i> <span>Sair</span>
                                </h:commandLink>

                            </h:form>  
                        </li>
                    </ul>
                </nav>
            </aside>
            <section class="row container-fluid"  >
                <div class="col-12">
                    <ui:insert name="body">Conteúdo</ui:insert>
                </div>
            </section>
        </div>

        <footer class="layout-footer">
            <div class="container">
                <span class="footer-copy">&copy; Adota Pet Web. Todos os direitos reservados.</span>
            </div>
        </footer>


        <!-- Bootstrap core JavaScript
                ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->

        <!--===============================================================================================-->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

        <script type="text/javascript">
        </script>
    </h:body>

</html>